"""Create initial tables

Revision ID: 314636c4c5d7
Revises: 91525149f0e9
Create Date: 2025-07-02 04:25:19.823416

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '314636c4c5d7'
down_revision: Union[str, Sequence[str], None] = '91525149f0e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
